### PR TITLE
ENH: this should have been 10 PRs

### LINKED ISSUE #7: Add some built-in configs for production plcs
The kfe plcs will be getting databases soon, this should be built-in to the tool

### LINKED ISSUE #10: Teach pmpsdb_client about export folder
Internal filepath:
/cds/group/pcds/pyps/apps/pmpsdb_server/pmps-db/export

- This is where the database files are exported to
- We need to open the file and send it to the PLC with a truncated name (so the PLC program opens the right file)
- We need to be able to compare against old files with what is loaded onto the PLC
- Show the timestamp of the latest exported version in the UI

```
$ ls -l export
-rw-rw-r-- 1 root root 12442 Jan 19 16:22 exported_plc-kfe-gatt-2023-01-19T16:22:00.673108.json
-rw-rw-r-- 1 root root 17520 Jan 19 16:05 exported_plc-kfe-motion-2023-01-19T16:05:15.995226.json
```

### PR DESCRIPTION
**Pull request by ZLLentz**
For reviewers: this just needs a red-flag skim. Further is welcome but I don't want to allocate time to fixing anything that isn't a major problem.

This is pretty large update that should have been 10 PRs, and would have been in normal operating conditions.

You can try the gui via `/cds/group/pcds/pyps/apps/pmpsdb_server/beta_client.sh`

I need to update https://confluence.slac.stanford.edu/display/L2SI/PMPSDB+Client+Transfer+Tool+Manual which also shows the version of the tool prior to this PR

This has a small amount of mess but I don't _really_ want to clean it up, I want to revisit this app on an as-needed basis rather than on a pre-emptive basis and move on to other projects.

Accomplished here

- Rework the cli to have more intuitive invocations
   - `pmpsdb gui` to open the gui with the correct plcs shown (just the ones for your area)
   - `pmpsdb upload-to plc-kfe-motion` is all you need to upload via the cli
   - You can check the file via `pmpsdb download-from plc-kfe-motion | jq`
   - Some others
- Reorganize the GUI
- Add some quick live checks: is the selected PLC ok?
- Adds a plc name lookup in the gui (from device name)
- Lots of bugfixes
- Probably others that I forget

I'm going to start adding issues with my remaining to-do items.

closes #7 
closes #10

### CODE REVIEW

**Comment by ZLLentz** [comment]
For reviewers: this just needs a red-flag skim. Further is welcome but I don't want to allocate time to fixing anything that isn't a major problem.

**Review by klauer — APPROVED** [review]
Looks pretty clean to me 👍

**Review by tangkong — APPROVED** [review]
Nothing screamed at me on my skim through.  The gui works nicely, the only thing that stood out was this somewhat strange string formatting (to be fair I'm not even sure if that's related to this PR)
image

**Comment by ZLLentz** [comment]
> strange string formatting

Funny story, that's a csv export/import/parsing error from data fields that contained commas in them

**Comment by ZLLentz** [comment]
I found one more bug that I'm going to fix prior to merge: the PLC status table doesn't update when you upload, so the check there can be stale

**Pull request merged**
